version: "3.8"

services:
  # MongoDB database for users
  users_db:
    image: mongo:8.0
    container_name: users_mongodb
    restart: unless-stopped
    ports:
      - "${USERS_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${USERS_MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${USERS_MONGO_INITDB_DATABASE}
    volumes:
      - users_mongodb_data:/data/db
    networks:
      - turbo_payments_network

  # MongoDB database for payments
  payments_db:
    image: mongo:8.0
    container_name: payments_mongodb
    restart: unless-stopped
    ports:
      - "${PAYMENTS_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PAYMENTS_MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${PAYMENTS_MONGO_INITDB_DATABASE}
    volumes:
      - payments_mongodb_data:/data/db
    networks:
      - turbo_payments_network

  # User Service
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: user_service
    restart: unless-stopped
    environment:
      USERS_DB_URL: ${USERS_DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: ${USER_SERVICE_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - users_db
    networks:
      - turbo_payments_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${USER_SERVICE_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Payment Service
  payment-service:
    build:
      context: .
      dockerfile: apps/payment-service/Dockerfile
    container_name: payment_service
    restart: unless-stopped
    environment:
      PAYMENTS_DB_URL: ${PAYMENTS_DB_URL}
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: ${PAYMENT_SERVICE_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    depends_on:
      - payments_db
      - user-service
    networks:
      - turbo_payments_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PAYMENT_SERVICE_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  users_mongodb_data:
    driver: local
  payments_mongodb_data:
    driver: local

networks:
  turbo_payments_network:
    driver: bridge